'@odata.context': /redfish/v1/$metadata#Bios.Bios
'@odata.etag': W/"04ACFB161408D7D7D79D6FED398B1F9C"
'@odata.id': /redfish/v1/systems/1/bios/settings/
'@odata.type': '#Bios.v1_0_0.Bios'
AttributeRegistry: BiosAttributeRegistryU43.v1_1_20
Attributes:
  AcpiHpet: Enabled
  AcpiRootBridgePxm: Enabled
  AcpiSlit: Enabled
  AdjSecPrefetch: Enabled
  AdminEmail: ''
  AdminName: ''
  AdminOtherInfo: ''
  AdminPhone: ''
  AdvCrashDumpMode: Disabled
  AsrStatus: Enabled
  AsrTimeoutMinutes: Timeout10
  AssetTagProtection: Unlocked
  AutoPowerOn: AlwaysPowerOff
  BootMode: Uefi
  BootOrderPolicy: RetryIndefinitely
  CollabPowerControl: Disabled
  ConsistentDevNaming: LomsAndSlots
  CustomPostMessage: ''
  DaylightSavingsTime: Disabled
  DcuIpPrefetcher: Enabled
  DcuStreamPrefetcher: Enabled
  Dhcpv4: Enabled
  EmbNicEnable: Auto
  EmbNicLinkSpeed: Auto
  EmbNicPCIeOptionROM: Enabled
  EmbSas1Aspm: Disabled
  EmbSas1Boot: TwentyFourTargets
  EmbSas1Enable: Auto
  EmbSas1LinkSpeed: Auto
  EmbSas1PcieOptionROM: Enabled
  EmbSata1Aspm: Disabled
  EmbVideoConnection: Auto
  EmbeddedDiagnostics: Enabled
  EmbeddedSata: Ahci
  EmbeddedSerialPort: Com2Irq3
  EmbeddedUefiShell: Enabled
  EmsConsole: Disabled
  EnabledCoresPerProc: 0
  EnergyEfficientTurbo: Disabled
  EraseUserDefaults: 'No'
  ExtendedAmbientTemp: Disabled
  ExtendedMemTest: Disabled
  F11BootMenu: Enabled
  FCScanPolicy: CardConfig
  FanFailPolicy: Shutdown
  FanInstallReq: EnableMessaging
  FlexLom1Aspm: Disabled
  HttpSupport: Auto
  HwPrefetcher: Enabled
  IntelDmiLinkFreq: Auto
  IntelPerfMonitoring: Disabled
  IntelProcVtd: Disabled
  IntelligentProvisioning: Enabled
  Ipv4Address: 0.0.0.0
  Ipv4Gateway: 0.0.0.0
  Ipv4PrimaryDNS: 0.0.0.0
  Ipv4SecondaryDNS: 0.0.0.0
  Ipv4SubnetMask: 0.0.0.0
  Ipv6Address: '::'
  Ipv6ConfigPolicy: Automatic
  Ipv6Duid: Auto
  Ipv6Gateway: '::'
  Ipv6PrimaryDNS: '::'
  Ipv6SecondaryDNS: '::'
  LlcPrefetch: Disabled
  LocalRemoteThreshold: Auto
  MaxMemBusFreqMHz: Auto
  MaxPcieSpeed: PerPortCtrl
  MemClearWarmReset: Disabled
  MemFastTraining: Enabled
  MemRefreshRate: Refreshx1
  MinProcIdlePkgState: NoState
  MinProcIdlePower: NoCStates
  MixedPowerSupplyReporting: Enabled
  NetworkBootRetry: Enabled
  NetworkBootRetryCount: 20
  NicBoot1: NetworkBoot
  NicBoot2: Disabled
  NvmeOptionRom: Enabled
  PciResourcePadding: Normal
  PciSlot2Bifurcation: Auto
  PostBootProgress: Disabled
  PostDiscoveryMode: Auto
  PostF1Prompt: Delayed20Sec
  PostVideoSupport: DisplayAll
  PowerButton: Enabled
  PowerOnDelay: NoDelay
  PowerRegulator: StaticHighPerf
  PreBootNetwork: Auto
  PrebootNetworkEnvPolicy: Auto
  PrebootNetworkProxy: ''
  ProcAes: Enabled
  ProcHyperthreading: Disabled
  ProcTurbo: Enabled
  ProcVirtualization: Disabled
  ProcX2Apic: Disabled
  ProductId: P06963-B21
  RedundantPowerSupply: BalancedMode
  RemovableFlashBootSeq: ExternalKeysFirst
  RestoreDefaults: 'No'
  RestoreManufacturingDefaults: 'No'
  RomSelection: CurrentRom
  SataSecureErase: Disabled
  SaveUserDefaults: 'No'
  SecStartBackupImage: Disabled
  SecureBootStatus: Disabled
  SerialConsoleBaudRate: BaudRate115200
  SerialConsoleEmulation: Vt100Plus
  SerialConsolePort: Auto
  SerialNumber: CN7916016Y
  ServerAssetTag: ''
  ServerConfigLockStatus: Disabled
  ServerName: ''
  ServerOtherInfo: ''
  ServerPrimaryOs: ''
  ServiceEmail: ''
  ServiceName: ''
  ServiceOtherInfo: ''
  ServicePhone: ''
  SetupBrowserSelection: Auto
  SgxEnable: Disabled
  SgxLaunchControlPolicy: Unlocked
  SgxLePublicKeyHash0: ''
  SgxLePublicKeyHash1: ''
  SgxLePublicKeyHash2: ''
  SgxLePublicKeyHash3: ''
  ThermalConfig: IncreasedCooling
  ThermalShutdown: Enabled
  TimeFormat: Utc
  TimeZone: Unspecified
  TpmChipId: None
  TpmFips: NotSpecified
  TpmState: NotPresent
  TpmType: NoTpm
  UefiOptimizedBoot: Enabled
  UefiSerialDebugLevel: Disabled
  UefiShellBootOrder: Disabled
  UefiShellScriptVerification: Disabled
  UefiShellStartup: Disabled
  UefiShellStartupLocation: Auto
  UefiShellStartupUrl: ''
  UefiShellStartupUrlFromDhcp: Disabled
  UrlBootFile: ''
  UrlBootFile2: ''
  UrlBootFile3: ''
  UrlBootFile4: ''
  UsbBoot: Enabled
  UsbControl: UsbEnabled
  UserDefaultsState: Disabled
  UtilityLang: English
  VirtualSerialPort: Com1Irq4
  VlanControl: Disabled
  VlanId: 0
  VlanPriority: 0
  WakeOnLan: Enabled
  WorkloadProfile: Custom
  iSCSIPolicy: SoftwareInitiator
Id: settings
Name: BIOS Pending Settings
