'@odata.context': /redfish/v1/$metadata#Bios.Bios
'@odata.etag': W/"0D240565D52ECFCFCF1EEA21B7B9FA0E"
'@odata.id': /redfish/v1/systems/1/bios/settings/
'@odata.type': '#Bios.v1_0_0.Bios'
AttributeRegistry: BiosAttributeRegistryU32.v1_2_02
Attributes:
  AcpiHpet: Enabled
  AcpiRootBridgePxm: Enabled
  AcpiSlit: Enabled
  AdjSecPrefetch: Enabled
  AdminEmail: ''
  AdminName: ''
  AdminOtherInfo: ''
  AdminPhone: ''
  AdvCrashDumpMode: Disabled
  AdvancedMemProtection: AdvancedEcc
  AsrStatus: Enabled
  AsrTimeoutMinutes: Timeout10
  AssetTagProtection: Unlocked
  AutoPowerOn: AlwaysPowerOff
  BootMode: Uefi
  BootOrderPolicy: RetryIndefinitely
  ChannelInterleaving: Enabled
  CollabPowerControl: Disabled
  ConsistentDevNaming: LomsAndSlots
  CustomPostMessage: ''
  DaylightSavingsTime: Disabled
  DcuIpPrefetcher: Enabled
  DcuStreamPrefetcher: Enabled
  Dhcpv4: Enabled
  DirectToUpi: Auto
  DynamicPowerCapping: Disabled
  EmbNicEnable: Auto
  EmbNicLinkSpeed: Auto
  EmbNicPCIeOptionROM: Enabled
  EmbSas1Aspm: Disabled
  EmbSas1Boot: TwentyFourTargets
  EmbSas1Enable: Auto
  EmbSas1LinkSpeed: Auto
  EmbSas1PcieOptionROM: Enabled
  EmbSata1Aspm: Disabled
  EmbSata2Aspm: Disabled
  EmbVideoConnection: Auto
  EmbeddedDiagnostics: Enabled
  EmbeddedSata: Ahci
  EmbeddedSerialPort: Com2Irq3
  EmbeddedUefiShell: Enabled
  EmsConsole: Disabled
  EnabledCoresPerProc: 0
  EnergyEfficientTurbo: Disabled
  EnergyPerfBias: MaxPerf
  EraseUserDefaults: 'No'
  ExtendedAmbientTemp: Disabled
  ExtendedMemTest: Disabled
  F11BootMenu: Enabled
  FCScanPolicy: CardConfig
  FanFailPolicy: Shutdown
  FanInstallReq: EnableMessaging
  FlexLom1Aspm: Disabled
  HttpSupport: Auto
  HwPrefetcher: Enabled
  IntelDmiLinkFreq: Auto
  IntelNicDmaChannels: Enabled
  IntelPerfMonitoring: Disabled
  IntelProcVtd: Enabled
  IntelUpiFreq: Auto
  IntelUpiLinkEn: Auto
  IntelUpiPowerManagement: Disabled
  IntelligentProvisioning: Enabled
  InternalSDCardSlot: Disabled
  Ipv4Address: 0.0.0.0
  Ipv4Gateway: 0.0.0.0
  Ipv4PrimaryDNS: 0.0.0.0
  Ipv4SecondaryDNS: 0.0.0.0
  Ipv4SubnetMask: 0.0.0.0
  Ipv6Address: '::'
  Ipv6ConfigPolicy: Automatic
  Ipv6Duid: Auto
  Ipv6Gateway: '::'
  Ipv6PrimaryDNS: '::'
  Ipv6SecondaryDNS: '::'
  LLCDeadLineAllocation: Enabled
  LlcPrefetch: Disabled
  LocalRemoteThreshold: Auto
  MaxMemBusFreqMHz: Auto
  MaxPcieSpeed: PerPortCtrl
  MemClearWarmReset: Disabled
  MemFastTraining: Enabled
  MemMirrorMode: Full
  MemPatrolScrubbing: Disabled
  MemRefreshRate: Refreshx1
  MemoryControllerInterleaving: Auto
  MemoryRemap: NoAction
  MinProcIdlePkgState: NoState
  MinProcIdlePower: NoCStates
  MixedPowerSupplyReporting: Enabled
  NetworkBootRetry: Enabled
  NetworkBootRetryCount: 20
  NicBoot1: NetworkBoot
  NicBoot2: Disabled
  NicBoot3: Disabled
  NicBoot4: Disabled
  NodeInterleaving: Disabled
  NumaGroupSizeOpt: Clustered
  NvmeOptionRom: Enabled
  OpportunisticSelfRefresh: Disabled
  PciPeerToPeerSerialization: Disabled
  PciResourcePadding: Normal
  PciSlot1Aspm: Disabled
  PciSlot1Bifurcation: Auto
  PciSlot1Enable: Auto
  PciSlot1LinkSpeed: Auto
  PciSlot1OptionROM: Enabled
  PciSlot2Bifurcation: Auto
  PersistentMemBackupPowerPolicy: WaitForBackupPower
  PostBootProgress: Disabled
  PostDiscoveryMode: Auto
  PostF1Prompt: Delayed20Sec
  PostVideoSupport: DisplayAll
  PowerButton: Enabled
  PowerOnDelay: NoDelay
  PowerRegulator: StaticHighPerf
  PreBootNetwork: Auto
  PrebootNetworkEnvPolicy: Auto
  PrebootNetworkProxy: ''
  ProcAes: Enabled
  ProcHyperthreading: Enabled
  ProcTurbo: Enabled
  ProcVirtualization: Enabled
  ProcX2Apic: Disabled
  ProcessorConfigTDPLevel: Normal
  ProcessorJitterControl: Disabled
  ProcessorJitterControlFrequency: 0
  ProcessorJitterControlOptimization: ZeroLatency
  ProductId: 867959-B21
  RedundantPowerSupply: BalancedMode
  RemovableFlashBootSeq: ExternalKeysFirst
  RestoreDefaults: 'No'
  RestoreManufacturingDefaults: 'No'
  RomSelection: CurrentRom
  SataSecureErase: Disabled
  SaveUserDefaults: 'No'
  SecStartBackupImage: Disabled
  SecureBootStatus: Disabled
  SerialConsoleBaudRate: BaudRate115200
  SerialConsoleEmulation: Vt100Plus
  SerialConsolePort: Auto
  SerialNumber: CN7918014C
  ServerAssetTag: ''
  ServerConfigLockStatus: Disabled
  ServerName: ''
  ServerOtherInfo: ''
  ServerPrimaryOs: ''
  ServiceEmail: ''
  ServiceName: ''
  ServiceOtherInfo: ''
  ServicePhone: ''
  SetupBrowserSelection: Auto
  Sriov: Enabled
  StaleAtoS: Disabled
  SubNumaClustering: Disabled
  ThermalConfig: OptimalCooling
  ThermalShutdown: Enabled
  TimeFormat: Utc
  TimeZone: Unspecified
  TpmChipId: None
  TpmFips: NotSpecified
  TpmState: NotPresent
  TpmType: NoTpm
  UefiOptimizedBoot: Enabled
  UefiSerialDebugLevel: Disabled
  UefiShellBootOrder: Disabled
  UefiShellScriptVerification: Disabled
  UefiShellStartup: Disabled
  UefiShellStartupLocation: Auto
  UefiShellStartupUrl: ''
  UefiShellStartupUrlFromDhcp: Disabled
  UncoreFreqScaling: Maximum
  UpiPrefetcher: Enabled
  UrlBootFile: ''
  UrlBootFile2: ''
  UrlBootFile3: ''
  UrlBootFile4: ''
  UsbBoot: Enabled
  UsbControl: UsbEnabled
  UserDefaultsState: Disabled
  UtilityLang: English
  VirtualInstallDisk: Disabled
  VirtualSerialPort: Com1Irq4
  VlanControl: Disabled
  VlanId: 0
  VlanPriority: 0
  WakeOnLan: Enabled
  WorkloadProfile: Custom
  XptPrefetcher: Auto
  iSCSIPolicy: SoftwareInitiator
Id: settings
Name: BIOS Pending Settings
