AcpiRootBridgePxm: Enabled
AcpiSlit: Enabled
AdjSecPrefetch: Enabled
AdminEmail: ''
AdminName: ''
AdminOtherInfo: ''
AdminPassword: null
AdminPhone: ''
AdvancedMemProtection: AdvancedEcc
AsrStatus: Enabled
AsrTimeoutMinutes: '10'
AssetTagProtection: Unlocked
AutoPowerOn: AlwaysPowerOff
BootMode: Uefi
BootOrderPolicy: RetryIndefinitely
ChannelInterleaving: Enabled
CollabPowerControl: Disabled
ConsistentDevNaming: LomsOnly
CustomPostMessage: ''
DaylightSavingsTime: Disabled
DcuIpPrefetcher: Enabled
DcuStreamPrefetcher: Enabled
Description: This is the Platform/BIOS Configuration (RBSU) Pending Settings
Dhcpv4: Enabled
DynamicPowerCapping: Auto
DynamicPowerResponse: Fast
EmbNicEnable: Enabled
EmbSas1Boot: AllTargets
EmbSasEnable: Enabled
EmbSata1Enable: Enabled
EmbSata2Enable: Enabled
EmbVideoConnection: Auto
EmbeddedDiagnostics: Enabled
EmbeddedDiagsMode: Auto
EmbeddedSata: Ahci
EmbeddedSerialPort: Com1Irq4
EmbeddedUefiShell: Enabled
EmbeddedUserPartition: Disabled
EmsConsole: Disabled
EnergyPerfBias: MaxPerf
EraseUserDefaults: 'No'
ExtendedAmbientTemp: Disabled
ExtendedMemTest: Disabled
F11BootMenu: Enabled
FCScanPolicy: CardConfig
FanFailPolicy: Shutdown
FanInstallReq: EnableMessaging
HwPrefetcher: Enabled
IntelDmiLinkFreq: Auto
IntelNicDmaChannels: Enabled
IntelPerfMonitoring: Disabled
IntelProcVtd: Disabled
IntelQpiFreq: Auto
IntelQpiLinkEn: Auto
IntelQpiPowerManagement: Disabled
IntelligentProvisioning: Enabled
InternalSDCardSlot: Disabled
IoNonPostedPrefetching: Enabled
Ipv4Address: 0.0.0.0
Ipv4Gateway: 0.0.0.0
Ipv4PrimaryDNS: 0.0.0.0
Ipv4SecondaryDNS: 0.0.0.0
Ipv4SubnetMask: 0.0.0.0
Ipv6Duid: Auto
MaxMemBusFreqMHz: Auto
MaxPcieSpeed: MaxSupported
MemFastTraining: Enabled
MemPatrolScrubbing: Disabled
MinProcIdlePkgState: NoState
MinProcIdlePower: NoCStates
MixedPowerSupplyReporting: Enabled
Modified: '2019-06-13T13:03:17+08:00'
Name: BIOS Pending Settings
NetworkBootRetry: Enabled
NicBoot1: NetworkBoot
NicBoot2: Disabled
NicBoot3: Disabled
NicBoot4: Disabled
NmiDebugButton: Enabled
NodeInterleaving: Disabled
NumaGroupSizeOpt: Clustered
OldAdminPassword: null
OldPowerOnPassword: null
PciBusPadding: Enabled
PciSlot1Enable: Enabled
PcieExpressEcrcSupport: Disabled
PostF1Prompt: Delayed20Sec
PowerButton: Enabled
PowerOnDelay: 15Sec
PowerOnLogo: Enabled
PowerOnPassword: null
PowerProfile: MaxPerf
PowerRegulator: StaticHighPerf
PreBootNetwork: Auto
ProcAes: Enabled
ProcCoreDisable: 0
ProcHyperthreading: Disabled
ProcNoExecute: Enabled
ProcTurbo: Enabled
ProcVirtualization: Enabled
ProcX2Apic: Disabled
ProductId: 719064-B21
QpiBandwidthOpt: Balanced
QpiSnoopConfig: Standard
RedundantPowerSupply: BalancedMode
RemovableFlashBootSeq: ExternalKeysFirst
RestoreDefaults: 'No'
RestoreManufacturingDefaults: 'No'
RomSelection: CurrentRom
SataSecureErase: Disabled
SaveUserDefaults: 'No'
SecureBootStatus: Disabled
SerialConsoleBaudRate: '115200'
SerialConsoleEmulation: Vt100Plus
SerialConsolePort: Auto
SerialNumber: 6CU542XD35
ServerAssetTag: ''
ServerName: WIN-9SGJKH10E1M
ServerOtherInfo: ''
ServerPrimaryOs: ''
ServiceEmail: ''
ServiceName: ''
ServiceOtherInfo: ''
ServicePhone: ''
Sriov: Disabled
ThermalConfig: OptimalCooling
ThermalShutdown: Enabled
TimeFormat: Utc
TimeZone: UtcP8
TpmState: NotPresent
TpmType: NoTpm
Type: HpBios.1.2.0
UefiOptimizedBoot: Enabled
UefiPxeBoot: Auto
UefiShellBootOrder: Disabled
UefiShellStartup: Disabled
UefiShellStartupLocation: Auto
UefiShellStartupUrl: ''
UrlBootFile: ''
Usb3Mode: Auto
UsbBoot: Enabled
UsbControl: UsbEnabled
UtilityLang: English
VirtualInstallDisk: Disabled
VirtualSerialPort: Com2Irq3
VlanControl: Disabled
VlanId: 0
VlanPriority: 0
WakeOnLan: Enabled
links:
  self:
    href: /rest/v1/systems/1/bios/Settings
